# Creating Handcrafted Features
We will add some handcrafted features to improve the performance of our logistic regression models. We will aim to add 3 general features along with 2 features that are more sentiment focused.

In [1]:
%pip install nltk

Requirement already satisfied: nltk in c:\users\stian\miniconda3\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\stian\miniconda3\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\stian\miniconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\stian\miniconda3\lib\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in c:\users\stian\miniconda3\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in c:\users\stian\miniconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import os
import kagglehub
from kagglehub import KaggleDatasetAdapter

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from collections import Counter

import string

c:\Users\stian\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Load Datasets Without Handcrafted Features

In [3]:
TRAIN_FILE_PATH = os.path.join('no_handcrafted', 'mental_health_text_train.csv')
TEST_FILE_PATH = os.path.join('no_handcrafted', 'mental_health_text_test.csv')


df_train = pd.read_csv(TRAIN_FILE_PATH, index_col=0)
df_test = pd.read_csv(TEST_FILE_PATH, index_col=0)

## Load Depression and Happiness Datasets

In [4]:
depression_path = kagglehub.dataset_download('diegosilvadefrana/depression-dataset')

df_depression = pd.read_csv(f'{depression_path}/dataset.csv', encoding='utf8')

df_depression.head()

,title,content,score
0,"Regular check-in post, with information about ...",Welcome to /r/depression's check-in post - a p...,115
1,Our most-broken and least-understood rules is ...,We understand that most people who reply immed...,2365
2,Going back to college at 33 after 3 times of d...,"I've always wanted to go back to school, the c...",84
3,Crying alone all the time,All I wan is to be loved. I just want someone...,108
4,I genuinely don’t think I’ll ever be able to h...,"I don’t even drive, didn’t finish my high scho...",60

In [5]:
happy_path = kagglehub.dataset_download("ritresearch/happydb")

df_happy = pd.read_csv(f'{happy_path}/cleaned_hm.csv', encoding='utf8')

df_happy.head()

,hmid,wid,reflection_period,original_hm,cleaned_hm,modified,num_sentence,ground_truth_category,predicted_category
0,27673,2053,24h,I went on a successful date with someone I fel...,I went on a successful date with someone I fel...,True,1,NaN,affection
1,27674,2,24h,I was happy when my son got 90% marks in his e...,I was happy when my son got 90% marks in his e...,True,1,NaN,affection
2,27675,1936,24h,I went to the gym this morning and did yoga.,I went to the gym this morning and did yoga.,True,1,NaN,exercise
3,27676,206,24h,We had a serious talk with some friends of our...,We had a serious talk with some friends of our...,True,2,bonding,bonding
4,27677,6227,24h,I went with grandchildren to butterfly display...,I went with grandchildren to butterfly display...,True,1,NaN,affection

In [6]:
df_depression.isnull().sum()

df_depression = df_depression.dropna()

In [7]:
top_depression = df_depression.sort_values('score', ascending=False).head(10)
for i in range(10):
  print(f'#{i+1} ------------------------------------------------------')
  print(top_depression.iloc[i]['content'])

#1 ------------------------------------------------------
Literally what the title says, I’m in shock rn idek what to say really. We’ve been on 4 dates and instantly clicked and had so much in common and constantly talked and he was just awesome, had sex on our third date and it was amazing as well. I really thought I had found a good one. And then right before our 5th date he went radio silent and promptly stood me up at the restaurant. Or so I thought. I thought “oh well he probably got something better to do thank god it’s only been like 3 weeks and I didn’t get too invested” but I also really liked him and was hella mad. 4 whole days of me delving into every insecurity I ever had trying to find a reason he would ghost me like this and embarrass me by standing me up.

And then I met my friend (his coworker) who introduced him to me. I didn’t want to seem unpleasant or anything so I just told him to tell the guy I’m not mad that he stood me up, to then be met with the saddest look.

- D..did you not know?
- Know what?
- _____ died. He got into a car crash on the 6th and died. How did you not know that?

I was speechless. For days I thought this wonderful guy ghosted me for no reason and was terribly pissed with him. Turns out he got clipped by a reckless driver and died on his way to our date. I don’t even know how to react. I’m just so flabbergasted right now. I’ve known him for less than a month, how does one even deal with something like this?


ETA: Thank you all so much for your words and thoughts and it is incredibly heartwarming for me to hear. And I would like to extend my love and condolences to those of you who had been through similar situations. I would just like to answer some of your questions:

1. I'm honestly not bothered anymore about our relationship and the what-ifs simply because it had barely been a month and still very much premature, and any anger or resentment I had when I thought I was ghosted has subsided even before I knew of everything and I don't feel much guilt about that anger as I know it was justified due to me not knowing of his demise. However, I still feel very sad simply because this guy is genuinely a very great person with such a promising future that I have grown to respect and root for him even beyond romantic/sexual attraction. So knowing that all of that had been cut short is incredibly heartbreaking for me.

2. A lot of you guys have been asking why my friend would ask me how I didn't know of his death, or why he didn't tell me about the news or check up on me beforehand. The answer is simply that he just assumed I already knew. I gushed about this guy to my friend a lot and thanked him for introducing me to him, and apparently, he did the same about me to this friend too (my friend is his direct superior so they talk a lot), and even wanted to introduce me to his sister. So apparently my friend thought that he and I have become close enough that when the guy died I would somehow know. I have never met his sister or any of his family and never knew about his plans to introduce me to her. I simply told my friend that I didn't know and that was that, nothing left to say.

3. I don't plan on meeting or doing anything with his family or go to his funeral really, I was no more than a little blip in his 21-year life so there isn't any reason for me to get any deeper. I did, however, send a message to his sister through social media to give my condolences, only as a friend of course. She thanked me and that's it.

4. I'm not planning to go to therapy, at least for now and not for this (broke immigrant college student from a third-world country), but I've had amazing support from friends.

Anyway, thank you so much.
#2 ------------------------------------------------------
Edit: Thank you so much to everyone for your kind words. It breaks my heart to know how many of you have had relatable experiences to my own. I’m looking into therapy asap and am grateful to have so many genuinely helpful messages to look back at while I do my best to move forward. This has meant the world to me and I appreciate everyone who took the time to help.

I just found out a couple hours ago.

I don’t know what to do, I don’t know how to cope with this. We broke up two months ago. We cared for each other very much and had been together for two and half years. In that time in spite of loving each other very much we had issues that did not resolve even with countless discussions.

He called me last night to get closure and we talked for a few hours. He was trying to understand why I left and why I wasn’t ready or willing to try again. I did my best to explain that while I would always love him, I could not be with him.

He said that his main purpose in life right now was me, and to get to a point in where I’d be willing to get back together. I said that it wasn’t healthy to look at me that way, I told him that he should be motivated to improve his life for himself.
I also made it clear that his chance to work things out had been when we were together and I when I was trying, not after I had already been burnt out and left.

I told him to please respect my boundaries and to stop trying to convince me to change my mind.

He said a a tearful goodbye.

An hour later, at 2:30am he shot himself.

I am in absolute shock. I am horrified and sad and I don’t know what to do.

I feel so sick to my stomach and I keep going from emptiness, to crying, to anger that he would do this, and I feel completely useless.

If there is anyone who knows how to cope with this sort of situation, or has any advice, I would be very grateful because I am feeling so lost in this moment.
#3 ------------------------------------------------------
So I have had a stalker for about a decade. We met through mutual friends but after a few months of knowing each other, red flags and alarm bells went off and I cut ties with her.
She however, did not and thus started nearly a decade of the weirdest stalking ever.

She would and still does, copy everything possible she can from me, from dying her hair, buying the same clothes as me, claiming to work in the same company as me, copy pasting my instagram posts, twitter status, stealing my holiday photos and photoshopping me out of them to look like they were hers, showing up to places she knows I would be ect. It's been really bizzare but as she hasn't don't anything physical, I was unable to get the law involved.

In 2020, my husband and I got pregnant but unfortunately suffered a miscarriage. Before we lost our baby we had put up a announcement on Facebook saying we were going to have a baby. I'm pretty good with graphic design so I designed it myself. I was heart broken after the miscarriage so took it down a week after the loss.

Fast forward to last September, when my stalker announced her pregnancy. Where, you guessed it, she used my custom announcement with just the names changed. It was wild, and more than a few people noticed how weird it was that she had kept on to the announcement for nearly 3 years just in case should she ever have a chance to use it.

It was then, I decided to play a little game.

She knew I was very close to my grandfather that passed away. If we had had our baby and it was a boy, I has intended to name him after my grandfather. I never stated the name publicly, but saw this as an opportunity to mess with her.

I posted about how I wished I could have called my baby "jack" after my grandfather and how much the name meant to me. My grandfather's name is most certainly not jack.

So, as predicted, guess what name she decided to name her baby boy? That's right. JACK.
she is so far unaware that jack was a completely random name and not even close to my grandfather's name that I care about. I plan on dropping the ball that it's the wrong name in a few years when It'll be impossible for her to change it.

Anyway, it's just made me laugh so hard that she would go that far and in turn named a whole other human being a random name just out of spite. Thought reddit would enjoy the bizzareness of it all.


------   Edit as people keep asking. -------

Yes, my social media is private. However, she has used fake profiles in the past pretending to be coworkers, friends, relatives ect. It has been a hard task keeping up and find them all and it's frankly exhausting so I just don't anymore. I have a public twitter due to my work so while I keep it as non personal as possible, I have to keep it public. I am in a creative field and use it as my portfolio.

The Facebook Post was set to friends of friends as I don't have a lot of my husbands family on there and he wished to share it with them. Its the only way I have figured that she found the post.

She has scrolled through friends socials to find anything she can about me (such as my holiday photos from a friends trip), and has stalked me in real life, such as following my mother around our town, turning up to my place of work, hanging out around my local store and following me around while I do groceries. If blocking and privating everything would have stopped her, it would have ended years ago but unfortunately, it has not been the case. I really wish it was that easy.
#4 ------------------------------------------------------
Last night I could hear my roommate verbally degrading her boyfriend which sadly enough is pretty normal and I didn’t think much of it since she normally does it as a way of humiliating him since she knows people are listening. I couldn’t bare listening anymore and decided to blast the TV but then I hear her getting physical and I can hear her choking him while he’s sobbing and begging her to stop. I began to panic wondering if I should intervene or just call 911 since I wanted to stop it from happening right away and was genuinely scared my roommate wasn’t fine. He is genuinely a nice guy and isn’t deserving of being treated that way but I also didn’t want to ruin her life since her career requires having a clean record. I don’t know why I still feel guilty and like I made the wrong choice but I can’t unhear him squealing and begging her to stop choking him.
Did I do the right thing?

Just for clarification, the whole ordeal went on for about 30 minutes until the cops came and intervened, she was beating him as well.
Edit: I was the one who called the cops once I heard it get more violent
I also turned the TV up because I wanted him to think I couldn’t hear anything which I thought would make him less embarrassed and humiliated, it wasnt trying to drown out the abuse, sounds dumb now but that’s how I was thinking at the time.





Edit for those who can’t see my comments: She ended up lying about having her parents come to pick her up and ended up taking off with the boyfriend and their belongings violating her court order of no contact, I am trying to locate the boyfriend and inform the police but haven’t had any luck, I really hope she doesn’t do anything to him
#5 ------------------------------------------------------
So, last night, my wife and I watched this porn video together online. It’s of a couple having very loving and intimate sex. We touched each other. It led to some really deep, emotionally connected sex between us. She fell asleep, and I grabbed my phone to close out the video, and I just happened to see the comment section when it minimized:

“I haven't enjoyed myself so much since my only true love passed away 23years ago. She made love to me just like that. Thanks for the beautiful experience of watching you two and for helping me relive some very intimate memories. Enjoy each other forever.”

I couldn’t help it. I legit teared up, y’all. Enjoy the fuck out of that special love if you’re lucky enough to have it.
#6 ------------------------------------------------------
I was making out with a guy (first time we see eachother, have been texting for almost a month), and all of a sudden he grabbed my neck. I knew he was aggressive and I didnt mind because I was sort of into it. I was not fucking expecting him to squeeze my traquea and then FUCKING SLAP ME. I didnt wait for an explanation just blocked him on everything.
What the actual fuck just happened?

It’s Trachea* but that’s how it’s spelt in Spanish, lol.

Update:
Holy shit I was not expecting this to get as much traction as it did. I was just venting about a dude. I’ll clarify some things that may have gotten lost in translation.

Some of you said to slap him back but he’s a much bigger dude and as soon as it happened I wanted to get to a safe environment.

I was really close to my house so I was in a good place to run away. I did not meet him too far away.

It was not the first time I saw him. I met him at church and had seen him around. Also background checked him with his church friends who belong in my group. He was not a rando. He was the first person I went out on a date with after 2 years.

I also did clarify to him I am not into any of rough shit. He asked and I said I’m not into any tough play. So he did disrespect a boundary and essentially assaulted me.

As I said before, the first thing in my mind was to escape. And here in my country this things go unpunished and I’m most likely going to be shamed like some of the commenters here did, just in a bigger scale bc we’re still in a misogynistic society.

I love how many of you understood I was assaulted but decided to blame me because I said the word men. Grow up dude, not everything is about you.

Thank you all for being concerned with my safety. I am safe and away from him and I will do  everything in my power to keep it that way.

I did block him on everything but here in my country we don’t usually use iMessage since most of us don’t have an iPhone. So he messages me there apologizing. I am not ready to talk to him, I am still really angry, but I also think I might never do so.

And for clarification, he’s in his late 20s so the porn comments are likely to be on point.

ETA: I’m heading to the drs for my annual check up, so I’ll see there about my throat. Although I do not feel any obstructions.
#7 ------------------------------------------------------
Hello everyone, this has been frustrating me for over a day now. My cousin (27) came over to my house yesterday. With a straight face, he told me that he literally said he was thinking about asking my dad about \*marrying\* my 13 year old sister. I was dumb-founded, horrified, and really upset. My cousin, who I was close to for years, just told me he liked my 13 year old sister, who is not only underage but is his cousin. I sat for about 30 minutes, and I didn't blow up on him, as I wanted to see just how deep this man's thoughts were. I sat there interrogating him, asking "why not someone your age? Is it because it's family and it's easier? Why are you preying on someone who is a child?". He said ever since she was a "kid", he has just really "liked her". He kept telling me that I was too worried about the law, when the law wasn't my concern, it was the fact that he was viewing my younger sister as someone that he could be "interested in". After questioning him, he could tell I was frustrated and angry, and I asked him to leave. She's a child. By and large, he has not been around my younger sister, and it's only recently that he has had any kind of access to her, and even that access has been very limited. He took her out to the movies once recently, and my parents were uncomfortable with it and told him he can't take her out anymore. My sister does not live with me but with her parents. He has also told me strange things about how he bought the most expensive suit he could find, and wanted to take her out to dinner. I brushed these little things off, as I figured he was trying to be "family", and do nice things for his cousin. Now all of these things are starting to click in my head as being deeply problematic at a minimum. There's so many strange things about this. Why was he so comfortable about this idea? Why would he ask me about it? My perception of my cousin has significantly shifted, and at a bare minimum I consider him to be a predator and having attempted to groom my younger sister. I don't know what to do exactly, I have told my immediate family about this, and my parents both knew about this to some extent already. I don't know what legal action can be taken if any, other than just keeping my family away from him. I officially and not talking to my cousin anymore, and he will not be allowed anywhere near my family. I don't know what to do. I had to get this off of my chest though.

EDIT: I learned after speaking to my mom tonight, the reason he may have been so comfortable asking is because many in his side of the family have married first cousins. While that by itself is an issue to me, the fact that he's asking about a child makes this significantly worse. Also, I live in South Carolina, and he is from Alabama.
#8 ------------------------------------------------------
I \[47M\] have been with my wife \[42F\] for 23 years and have been married for 20. She's the only woman I've ever really been attracted to (and even then, I only really became attracted to her after we knew each other for a year and had dated for another) and the only one I've ever had sex with either. Once I felt that for her, my libido absolutely skyrocketed and it hasn't gone down since.

I've never told her quite how high my drive is. I find myself wanting her 3-4 times a day, but I don't want her to feel pressured or to think all I think about or want from her is sex. I adore her, and quite frankly, if I could make my sex drive truly be what she thinks it is (roughly the same as hers, that is), I absolutely would. It's very frustrating when I just want to cuddle or appreciate a conversation or a bath together or a movie and instead feel so horny.

I don't know if this is normal (I certainly know that the way I feel attraction isn't quite normal), but if it is, how does anyone deal with this? I've tried supplementing with masturbation, but it just doesn't scratch the right itch. I suppose at the end of the day it's just nice to say this, even if nothing changes I'll be perfectly happy, if always a touch frustrated with my body.

&#x200B;

Edit/Addition: I have posted an update (it's the only other post I've made)! In short, I told my wife and it went very, very well. Thank you all!
#9 ------------------------------------------------------
I posted yesterday (it's the only other post I've made) about how my sex drive has been very, very high ever since I started feeling sexually attracted to my wife (i.e. for the past 22 years), and after a lot of encouragement and discussion from commenters, I realized that I've worked myself up so much about telling her and have made it something to be worried about, even though really I shouldn't have felt that way.

This morning once I woke up, I told her that I had something to discuss with her, then I told her about what my drive really is, how I was worried about how she'd feel (and hence why I never mentioned that it was higher before), and that I didn't want her to feel pressured in the slightest about it, I just wanted to be honest with her (and I showed her the post too).

She then told me she actually had been feeling more randy in recent years but didn't want *me* to feel like she just wanted me for sex, then told me that I didn't have anything to worry about and she would have been very receptive even if I'd told her two decades ago. We kissed and had a bit of a laugh about how we'd worked ourselves up about this, and it was just so nice to let her know how I feel and to know how she feels about this.


Find the most common words

In [8]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

def get_frequency(df, content_name):
  '''
  Counts frequency of words and returns counter for all words
  '''

  text = ' '.join(df[content_name].dropna())
  tokens = word_tokenize(text.lower())
    
  ## Remove common stopwords
  stop_words = set(stopwords.words('english'))

  cleaned_tokens = []
  for token in tokens:
    if token not in stop_words and token.isalpha():
      cleaned_tokens.append(token)
  
  return Counter(cleaned_tokens)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\stian\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\stian\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\stian\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [9]:
dep_freq = get_frequency(df_depression, 'content')

happy_freq = get_frequency(df_happy, 'cleaned_hm')

In [10]:
dep_words = []
for word in dep_freq.most_common(25):
  dep_words.append(word[0])

happy_words = []
for word in happy_freq.most_common(25):
  happy_words.append(word[0])

In [11]:
def count_from_list(tokens, word_list):
  count = 0
  
  for token in tokens:
    if token in word_list:
      count += 1

  return count

def count_punctuation(tokens):
  count = 0
  for token in tokens:
    if token in string.punctuation:
      count += 1
  return count

In [12]:
text_len = []
token_count = []
punct_count = []
dep_count = []
happy_count = []

for row in df_train.values:
  text = row[0]
  tokens = word_tokenize(text)
  
  text_len.append(len(text))

  token_count.append(len(tokens))

  punct_count.append(count_punctuation(tokens))

  dep_count.append(count_from_list(tokens, dep_words))
  happy_count.append(count_from_list(tokens, happy_words))

df_train['text_length'] = text_len
df_train['token_count'] = token_count
df_train['punctuation_count'] = punct_count
df_train['depression_word_count'] = dep_count
df_train['happy_word_count'] = happy_count

In [13]:
text_len_test = []
token_count_test = []
punct_count_test = []
dep_count_test = []
happy_count_test = []

for i, row in enumerate(df_test.values):
  text = row[0]
  tokens = word_tokenize(text)

  text_len_test.append(len(text))

  token_count_test.append(len(tokens))

  punct_count_test.append(count_punctuation(tokens))
  
  dep_count_test.append(count_from_list(tokens, dep_words))
  happy_count_test.append(count_from_list(tokens, happy_words))

df_test['text_length'] = text_len_test
df_test['token_count'] = token_count_test
df_test['punctuation_count'] = punct_count_test
df_test['depression_word_count'] = dep_count_test
df_test['happy_word_count'] = happy_count_test

In [14]:
df_train.head()

,text,status,text_length,token_count,punctuation_count,depression_word_count,happy_word_count
3335,I have typed a message but I haven't yet sent ...,Normal,56,15,1,0,0
43240,gnite twitter world long day tomorrow night cl...,Normal,58,10,0,1,2
22622,"I am only 16 and I fucked up, I have a 1.2 GPA...",Suicidal,754,169,13,16,3
5526,"It's sad, when the electricity goes out while ...",Normal,97,20,1,0,0
30976,i can't believe how hot it is.,Normal,30,9,1,0,0

In [15]:
df_test.head()

,text,status,text_length,token_count,punctuation_count,depression_word_count,happy_word_count
29619,I make a good living and only want to get on w...,Normal,320,70,4,7,3
15959,I am a teenager. I want to cut myself. You can...,Suicidal,359,88,13,3,2
7391,Ã¢â¬ÅVisualizing your dreams down to the det...,Normal,130,21,3,1,1
5026,Hopefully SM will be more open and see the pot...,Normal,217,43,4,2,3
25225,I am not super suicidal right now but I still ...,Suicidal,421,96,5,6,0

In [17]:
dir_path = './handcrafted/'
df_train.to_csv(f'{dir_path}/mental_health_text_train_features.csv')
df_test.to_csv(f'{dir_path}/mental_health_text_test_features.csv')