In [17]:
%pip install kagglehub[pandas-datasets]
%pip install datasets

Requirement already satisfied: kagglehub[pandas-datasets] in c:\users\stian\miniconda3\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\stian\miniconda3\lib\site-packages (from kagglehub[pandas-datasets]) (0.1.16)
Requirement already satisfied: packaging in c:\users\stian\miniconda3\lib\site-packages (from kagglehub[pandas-datasets]) (24.1)
Requirement already satisfied: pyyaml in c:\users\stian\miniconda3\lib\site-packages (from kagglehub[pandas-datasets]) (6.0.2)
Requirement already satisfied: requests in c:\users\stian\miniconda3\lib\site-packages (from kagglehub[pandas-datasets]) (2.32.3)
Requirement already satisfied: tqdm in c:\users\stian\miniconda3\lib\site-packages (from kagglehub[pandas-datasets]) (4.66.5)
Requirement already satisfied: pandas in c:\users\stian\miniconda3\lib\site-packages (from kagglehub[pandas-datasets]) (2.2.3)
Requirement already satisfied: protobuf in c:\users\stian\miniconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub[pandas-datasets]) (7.34.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\stian\miniconda3\lib\site-packages (from pandas->kagglehub[pandas-datasets]) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\stian\miniconda3\lib\site-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\stian\miniconda3\lib\site-packages (from pandas->kagglehub[pandas-datasets]) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\stian\miniconda3\lib\site-packages (from pandas->kagglehub[pandas-datasets]) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\stian\miniconda3\lib\site-packages (from requests->kagglehub[pandas-datasets]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\stian\miniconda3\lib\site-packages (from requests->kagglehub[pandas-datasets]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\stian\miniconda3\lib\site-packages (from requests->kagglehub[pandas-datasets]) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\stian\miniconda3\lib\site-packages (from requests->kagglehub[pandas-datasets]) (2024.8.30)
Requirement already satisfied: colorama in c:\users\stian\miniconda3\lib\site-packages (from tqdm->kagglehub[pandas-datasets]) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\stian\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Collecting datasets
  Downloading datasets-4.8.3-py3-none-any.whl.metadata (19 kB)
Collecting filelock (from datasets)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\stian\miniconda3\lib\site-packages (from datasets) (2.2.1)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\stian\miniconda3\lib\site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\stian\miniconda3\lib\site-packages (from datasets) (2.32.3)
Requirement already satisfied: httpx<1.0.0 in c:\users\stian\miniconda3\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\stian\miniconda3\lib\site-packages (from datasets) (4.66.5)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Downloading huggingface_hub-1.7.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\stian\miniconda3\lib\site-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\stian\miniconda3\lib\site-packages (from datasets) (6.0.2)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.3-cp312-cp312-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: anyio in c:\users\stian\miniconda3\lib\site-packages (from httpx<1.0.0->datasets) (4.8.0)
Requirement already satisfied: certifi in c:\users\stian\miniconda3\lib\site-packages (from httpx<1.0.0->datasets) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\users\stian\miniconda3\lib\site-packages (from httpx<1.0.0->datasets) (1.0.7)
Requirement already satisfied: idna in c:\users\stian\miniconda3\lib\site-packages (from httpx<1.0.0->datasets) (3.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\stian\miniconda3\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.14.0)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting typer (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\stian\miniconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\stian\miniconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\stian\miniconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: colorama in c:\users\stian\miniconda3\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\stian\miniconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\stian\miniconda3\lib\site-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\stian\miniconda3\lib\site-packages (from pandas->datasets) (2024.2)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\stian\miniconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (24.3.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp312-cp312-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp312-cp312-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: six>=1.5 in c:\users\stian\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\stian\miniconda3\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Collecting click>=8.2.1 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\stian\miniconda3\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading datasets-4.8.3-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/526.8 kB ? eta -:--:--
   ---------------------------------------- 526.8/526.8 kB 8.5 MB/s eta 0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading huggingface_hub-1.7.2-py3-none-any.whl (618 kB)
   ---------------------------------------- 0.0/618.0 kB ? eta -:--:--
   ---------------------------------------- 618.0/618.0 kB 7.6 MB/s eta 0:00:00
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading multiprocess-0.70.19-py312-none-any.whl (150 kB)
Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---- ----------------------------------- 3.4/27.6 MB 18.3 MB/s eta 0:00:02
   --------- ------------------------------ 6.8/27.6 MB 17.5 MB/s eta 0:00:02
   --------------- ------------------------ 11.0/27.6 MB 18.1 MB/s eta 0:00:01
   -------------------- ------------------- 13.9/27.6 MB 17.1 MB/s eta 0:00:01
   ------------------------ --------------- 17.0/27.6 MB 16.8 MB/s eta 0:00:01
   ------------------------------ --------- 21.2/27.6 MB 17.0 MB/s eta 0:00:01
   ------------------------------------ --- 25.2/27.6 MB 17.3 MB/s eta 0:00:01
   ---------------------------------------- 27.6/27.6 MB 17.0 MB/s eta 0:00:00
Downloading xxhash-3.6.0-cp312-cp312-win_amd64.whl (31 kB)
Downloading aiohttp-3.13.3-cp312-cp312-win_amd64.whl (455 kB)
Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ---------------------------------------- 3.7/3.7 MB 19.9 MB/s eta 0:00:00
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl (44 kB)
Downloading multidict-6.7.1-cp312-cp312-win_amd64.whl (46 kB)
Downloading propcache-0.4.1-cp312-cp312-win_amd64.whl (41 kB)
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading yarl-1.23.0-cp312-cp312-win_amd64.whl (87 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: xxhash, shellingham, pyarrow, propcache, multidict, mdurl, hf-xet, fsspec, frozenlist, filelock, dill, click, annotated-doc, aiohappyeyeballs, yarl, multiprocess, markdown-it-py, aiosignal, rich, aiohttp, typer, huggingface-hub, datasets
  Attempting uninstall: click
    Found existing installation: click 8.1.8
    Uninstalling click-8.1.8:
      Successfully uninstalled click-8.1.8
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 annotated-doc-0.0.4 click-8.3.1 datasets-4.8.3 dill-0.4.1 filelock-3.25.2 frozenlist-1.8.0 fsspec-2026.2.0 hf-xet-1.4.2 huggingface-hub-1.7.2 markdown-it-py-4.0.0 mdurl-0.1.2 multidict-6.7.1 multiprocess-0.70.19 propcache-0.4.1 pyarrow-23.0.1 rich-14.3.3 shellingham-1.5.4 typer-0.24.1 xxhash-3.6.0 yarl-1.23.0
Note: you may need to restart the kernel to use updated packages.

In [18]:
import pandas as pd
from kagglehub import KaggleDatasetAdapter
from datasets import load_dataset

# Preprocessing
## First Primary datasets

In [19]:
## Load Mental Health Text Classification Dataset
df_mhtc = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,
                                 "priyangshumukherjee/mental-health-text-classification-dataset",
                                 "mental_health_combined_test.csv")

df_mhtc.head(10)

C:\Users\stian\AppData\Local\Temp\ipykernel_3020\491622150.py:2: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_mhtc = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,

                                                text   status
0  i don't understand whats wrong with me. i don'...  Anxiety
1  usually when i have anxiety just chatting with...  Anxiety
2  well, i've had anxiety and panic syndrome for ...  Anxiety
3  for the most minimal of things, like standing ...  Anxiety
4  i stay away from family and live with my roomm...  Anxiety
5  i'm very ecstatic, i got a job that literally ...  Anxiety
6  i've been feeling anxious today, but it's alwa...  Anxiety
7  i quit my job today. it was fucking terrible. ...  Anxiety
8  after months of being stuck in a loop of stayi...  Anxiety
9  i’m at a resort with my friends and their pare...  Anxiety

In [20]:
## Load Mental Health Text Classification Dataset
df_mhtc = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,
                                 "priyangshumukherjee/mental-health-text-classification-dataset",
                                 "mental_health_combined_test.csv")

print(df_mhtc.info())
df_mhtc.head(10)

C:\Users\stian\AppData\Local\Temp\ipykernel_3020\3028018092.py:2: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_mhtc = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    992 non-null    object
 1   status  992 non-null    object
dtypes: object(2)
memory usage: 15.6+ KB
None

                                                text   status
0  i don't understand whats wrong with me. i don'...  Anxiety
1  usually when i have anxiety just chatting with...  Anxiety
2  well, i've had anxiety and panic syndrome for ...  Anxiety
3  for the most minimal of things, like standing ...  Anxiety
4  i stay away from family and live with my roomm...  Anxiety
5  i'm very ecstatic, i got a job that literally ...  Anxiety
6  i've been feeling anxious today, but it's alwa...  Anxiety
7  i quit my job today. it was fucking terrible. ...  Anxiety
8  after months of being stuck in a loop of stayi...  Anxiety
9  i’m at a resort with my friends and their pare...  Anxiety

In [21]:
## Load Sentiment Analysis for Mental Health
df_safmh = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,
                                 "priyangshumukherjee/mental-health-text-classification-dataset",
                                 "mental_health_combined_test.csv")

print(df_safmh.info())
df_safmh.head(10)

C:\Users\stian\AppData\Local\Temp\ipykernel_3020\1907873127.py:2: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_safmh = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    992 non-null    object
 1   status  992 non-null    object
dtypes: object(2)
memory usage: 15.6+ KB
None

                                                text   status
0  i don't understand whats wrong with me. i don'...  Anxiety
1  usually when i have anxiety just chatting with...  Anxiety
2  well, i've had anxiety and panic syndrome for ...  Anxiety
3  for the most minimal of things, like standing ...  Anxiety
4  i stay away from family and live with my roomm...  Anxiety
5  i'm very ecstatic, i got a job that literally ...  Anxiety
6  i've been feeling anxious today, but it's alwa...  Anxiety
7  i quit my job today. it was fucking terrible. ...  Anxiety
8  after months of being stuck in a loop of stayi...  Anxiety
9  i’m at a resort with my friends and their pare...  Anxiety

In [30]:
## Load Ourafla's Dataset

df_ourafla = pd.read_csv("hf://datasets/ourafla/Mental-Health_Text-Classification_Dataset/mental_health_feature_engineered.csv")
print(df_ourafla.info())
df_ourafla.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49612 entries, 0 to 49611
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unique_ID             40012 non-null  float64
 1   text                  49612 non-null  object
 2   status                49612 non-null  object
 3   text_length           40012 non-null  float64
 4   word_count            40012 non-null  float64
 5   num_urls              40012 non-null  float64
 6   num_emojis            40012 non-null  float64
 7   num_special_chars     40012 non-null  float64
 8   num_excess_punct      40012 non-null  float64
 9   avg_word_length       40012 non-null  float64
 10  stopword_ratio        40012 non-null  float64
 11  type_token_ratio      40012 non-null  float64
 12  polarity              40012 non-null  float64
 13  subjectivity          40012 non-null  float64
 14  noun_ratio            40012 non-null  float64
 15  verb_ratio            40012 non-null  float64
 16  adj_ratio             40012 non-null  float64
 17  adv_ratio             40012 non-null  float64
 18  has_suicidal_keyword  40012 non-null  object
 19  has_stress_keyword    40012 non-null  object
 20  has_help_keyword      40012 non-null  object
dtypes: float64(16), object(5)
memory usage: 7.9+ MB
None

,Unique_ID,text,status,text_length,word_count,num_urls,num_emojis,num_special_chars,num_excess_punct,avg_word_length,...,type_token_ratio,polarity,subjectivity,noun_ratio,verb_ratio,adj_ratio,adv_ratio,has_suicidal_keyword,has_stress_keyword,has_help_keyword
0,0.0,oh my gosh,Anxiety,0.001678,0.007576,0.0,0.0,0.0,0.0,0.005395,...,1.000000,0.50000,0.0000,0.0,0.000000,0.333333,0.000000,False,False,False
1,1.0,"trouble sleeping, confused mind, restless hear...",Anxiety,0.046980,0.034091,0.0,0.0,0.0,0.0,0.015152,...,1.000000,0.35000,0.4500,0.0,0.100000,0.000000,0.000000,False,False,False
2,2.0,"All wrong, back off dear, forward doubt. Stay ...",Anxiety,0.058725,0.049242,0.0,0.0,0.0,0.0,0.012200,...,0.926576,0.37500,0.4500,0.0,0.000000,0.071429,0.000000,False,False,False
3,3.0,I've shifted my focus to something else but I'...,Anxiety,0.044463,0.037879,0.0,0.0,0.0,0.0,0.012178,...,1.000000,0.50000,0.0000,0.0,0.272727,0.090909,0.000000,False,False,False
4,4.0,"I'm restless and restless, it's been a month n...",Anxiety,0.053691,0.049242,0.0,0.0,0.0,0.0,0.010724,...,1.000000,0.34375,0.6875,0.0,0.000000,0.000000,0.000000,False,False,False
5,5.0,"every break, you must be nervous, like somethi...",Anxiety,0.057047,0.049242,0.0,0.0,0.0,0.0,0.011708,...,1.000000,0.25000,0.9000,0.0,0.071429,0.071429,0.000000,False,False,False
6,6.0,"I feel scared, anxious, what can I do? And may...",Anxiety,0.058725,0.060606,0.0,0.0,0.0,0.0,0.008771,...,0.939533,0.56250,1.0000,0.0,0.058824,0.176471,0.088235,False,False,False
7,7.0,Have you ever felt nervous but didn't know why?,Anxiety,0.032718,0.030303,0.0,0.0,0.0,0.0,0.011134,...,1.000000,0.50000,0.0000,0.0,0.000000,0.000000,0.000000,False,False,False
8,8.0,"I haven't slept well for 2 days, it's like I'm...",Anxiety,0.052013,0.049242,0.0,0.0,0.0,0.0,0.010232,...,1.000000,0.12500,1.0000,0.0,0.000000,0.071429,0.000000,False,False,False
9,9.0,"I'm really worried, I want to cry.",Anxiety,0.021812,0.022727,0.0,0.0,0.0,0.0,0.009986,...,1.000000,0.60000,0.2000,0.0,0.000000,0.142857,0.214286,False,False,False